### ISSUE TITLE
Create Order endpoint and save to DB

### ISSUE THREAD

**Issue by satadipmukherjee** [dockersamples/atsea-sample-shop-app#104]
I do not want to implement any of the Reverse Proxy / Payment features but just want the React Front End OMS coupled to the REST-Spring backend with the orders saved to the DB.

Through API the Create Order and all services are working perfectly but through the React Front End unable to store the orders in the DB.

In the CheckoutContainer.js I am seeing the comments in the Handlesubmit function :

// This data will be used for create order endpoint
// TODO: CreateOrder

Does this indicate that these functionality are yet to be implemented ?

However, on clicking on "Complete Order" I am receiving the Order Placed successfully message but the items and the orders do not appear to be getting stored on the PSQL DB. Tried incrementing the Order ID other than '0' value also.

Can anybody help me in figuring out the implementation of the Order Endpoint and how I can store it in a external DB since I am totally novice to JS and need this as a part of a Cloud project.

**Comment by BretFisher** [comment]
Closing issues due to repo archiving. Feel free to fork so it can live on!
