### ISSUE TITLE
Stopped Working at Noon on November 4th

### ISSUE THREAD

**Issue by Bharzog** [dockersamples/atsea-sample-shop-app#105]
docker-compose up --build run in the app directory results in the following error messages. This started happening today.

atsea_appserver_1 exited with code 1
atsea_payment_gateway_1 exited with code 126
reverse_proxy_1    | 2019/11/04 18:56:22 [emerg] 1#1: host not found in upstream                                                 "appserver" in /etc/nginx/nginx.conf:46
reverse_proxy_1    | nginx: [emerg] host not found in upstream "appserver" in /e                                                tc/nginx/nginx.conf:46
atsea_reverse_proxy_1 exited with code 1

**Comment by BretFisher** [comment]
Closing issues due to repo archiving. Feel free to fork so it can live on!
