### ISSUE TITLE
Database is uninitialized 

### ISSUE THREAD

**Issue by gowrisankarp** [dockersamples/atsea-sample-shop-app#119]
atabase_1         | Error: Database is uninitialized and superuser password is not specified.
database_1         |        You must specify POSTGRES_PASSWORD to a non-empty value for the
database_1         |        superuser. For example, "-e POSTGRES_PASSWORD=password" on "docker run".
database_1         |
database_1         |        You may also use "POSTGRES_HOST_AUTH_METHOD=trust" to allow all
database_1         |        connections without a password. This is *not* recommended.
database_1         |
database_1         |        See PostgreSQL documentation about "trust":

**Comment by BretFisher** [comment]
Closing issues due to repo archiving. Feel free to fork so it can live on!
