### ISSUE TITLE
Run as non-root user

### ISSUE THREAD

**Issue by ManoMarks** [dockersamples/atsea-sample-shop-app#13]
Set the app to run as a non-root user.

**Comment by Ed42** [comment]
Is that why I get this running as non-root?
```

**Comment by cecton** [comment]
> ERROR: datastore for scope "global" is not initialized

@Ed42 No that come from the overlay network. You need to initialize your Docker daemon as a Swarm for it to work. I don't know if you can run it without the Swarm, the doc makes it feel optional.

**Comment by spara** [comment]
Run as non root users:  https://github.com/dockersamples/atsea-sample-shop-app/commit/2a40c44afc9cc916704593d2ca8ce52304ed1261
