### ISSUE TITLE
update component tests

### ISSUE THREAD

**Issue by jessvalarezo** [dockersamples/atsea-sample-shop-app#36]

**Comment by gasperlf** [comment]
docker-compose up --build
WARNING: The Docker Engine you're using is running in swarm mode.

Compose does not use swarm mode to deploy services to multiple nodes in a swarm. All containers will be scheduled on the current node.

To deploy your application across the swarm, use `docker stack deploy`.

Building appserver
Step 1/20 : FROM node:latest AS storefront
ERROR: Service 'appserver' failed to build: Error parsing reference: "node:latest AS storefront" is not a valid repository/tag: invalid reference format

**Comment by ManoMarks** [comment]
@gasperlf this requires multi-stage build which is available in Docker 17.05 CE Edge. If you're using stable it won't work. It is scheduled for 17.06 stable.

**Comment by ManoMarks** [comment]
@jessvalarezo is this still an open issue, should we close?

**Comment by gasperlf** [comment]
@ManoMarks I'm using Docker version 17.03.1-ce, build c6d412e

**Comment by ManoMarks** [comment]
@gasperlf yes, it wasn't available in 17.03. If you shift to the edge channel or wait for the 17.06 you'll be able to use it.
