### ISSUE TITLE
URLs are case sensitive

### ISSUE THREAD

**Issue by ManoMarks** [dockersamples/atsea-sample-shop-app#4]
URLs shouldn't be case sensitive, it just feels wrong. Might be helpful:
http://stackoverflow.com/questions/12684183/case-insensitive-mapping-for-spring-mvc-requestmapping-annotations

**Comment by spara** [comment]
OK, I'll put this on the list of things to implement

**Comment by ManoMarks** [comment]
@spara was this fixed?

**Comment by spara** [comment]
Fixed in https://github.com/dockersamples/atsea-sample-shop-app/commit/addb0c85dc808b3a7602805343a1ea29cd6d79a1
