### ISSUE TITLE
Add simplified version

### ISSUE THREAD

**Issue by ManoMarks** [dockersamples/atsea-sample-shop-app#89]
Add in a simplified deployment without secrets

**Comment by spara** [comment]
I've added docker-compose-dev.yml which only contains the app server and the database, it still uses secrets but there isn't a need for a certificate or a staging token since those pieces are not used. Is this sufficient or should I write a compose file that uses environmental variables?

**Comment by ManoMarks** [comment]
That's good. Thanks.
