### ISSUE TITLE
Ahead of formal releases with sample apps?

### ISSUE THREAD

**Issue by squillace** [dockersamples/atsea-sample-shop-app#91]
Hi, was trying this app on docker for mac where I have the very newest version:
```
Client:
 Version:      17.03.1-ce
 API version:  1.27
 Go version:   go1.7.5
 Git commit:   c6d412e
 Built:        Tue Mar 28 00:40:02 2017
 OS/Arch:      darwin/amd64
```

Unfortunately, the new stuff has multi-build "from node:latest AS story..." format, which blows up in the released and installed version of the produce. Methinks you're going a bit too fast for a sample app. :-) I'll regress back to a commit at that time, but just wanted you to know that the advertised version of your product can't run the sample app.

**Comment by squillace** [comment]
```
ralph@macbookpro  ~/work/nogo/atsea-sample-shop-app   master ●  docker stack deploy -c docker-stack.yml atsea
unsupported Compose file version: 3.2
 ✘ ralph@macbookpro  ~/work/nogo/atsea-sample-shop-app   master ●  docker-compose --version
docker-compose version 1.11.2, build dfed245
```

Of course, I could manually update everything. But I expect the samples to work against the company's own marketed installer version. Am I unreasonable?

**Comment by spara** [comment]
Apologies, Docker 17.05 CE Edge supports multi-stage builds. Will add a note in README
