### ISSUE TITLE
ERROR: Version in "./docker-compose.yml" is unsupported.

### ISSUE THREAD

**Issue by cassiusvm** [dockersamples/atsea-sample-shop-app#92]
Hello,

I followed the instructions for "Docker Community Edition for Ubuntu" at https://store.docker.com/editions/community/docker-ce-server-ubuntu to install Docker on Ubuntu 16.04 LTS

I did do: $ git clone https://github.com/dockersamples/atsea-sample-shop-app.git

I followed the instructions on README.md

First issue:
$ docker secret create revprox_cert certs/domain.crt
Error response from daemon: This node is not a swarm manager. Use "docker swarm init" or "docker swarm join" to connect this node to swarm and try again.

So I did do: $ docker swarm init

Second issue:
$ docker-compose up --build
O programa 'docker-compose' não está instalado no momento. Você pode instalá-lo digitando:
sudo apt install docker-compose

So I did do: $ sudo apt install docker-compose

Third issue:
$ docker-compose up --build
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a version of "2" (or "2.0") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

How to solve this last issue, please? I think I am using the wrong docker-compose

**Comment by spara** [comment]
Hi,

This tutorial uses Docker CE 17.05 Edge or higher and Compose 1.13.0, please see this [gist](https://gist.github.com/spara/400c0e8e156bb985de7f85910cd44e7e) to install these versions on Ubuntu 16.04 LTS.

**Comment by cassiusvm** [comment]
Hello,

Thanks.
