### ISSUE TITLE
Unable to deploy stack on a single node swarm

### ISSUE THREAD

**Issue by bquenin** [dockersamples/atsea-sample-shop-app#98]
Following the steps described [here](https://github.com/dockersamples/atsea-sample-shop-app#deploy-to-a-swarm) will not lead to a running stack. Indeed, some of the services are constrained to run on `worker` nodes, which is not the case while running a single node swarm locally.

**Comment by AlicanAkkus** [comment]
hi @bquenin ,
I've fixed this error on my repository. You can try this -> https://github.com/AlicanAkkus/atsea-sample-shop-app

Could you please share result after the test?

**Comment by bquenin** [comment]
Hi @AlicanAkkus, I have the same (erroneous) behavior because the placement constraints are still requiring a `worker` node:
- https://github.com/AlicanAkkus/atsea-sample-shop-app/blob/master/docker-stack.yml#L27-L30
- https://github.com/AlicanAkkus/atsea-sample-shop-app/blob/master/docker-stack.yml#L75-L81

**Comment by arush-sal** [comment]
@bquenin I think the application's docker-stack.yml was written with at least 1 worker, 1 manager node in mind, which should be a minimalistic docker swarm (lab)setup. But yes, if you wish to deploy it on manager i.e single node setup then you can simply remove the placement constraints from @AlicanAkkus's docker-stack.yml file and it will run w/o any issue(s).

**Comment by bquenin** [comment]
@arush-sal Thanks for your feedback. I know how to fix the issue :) I just wanted to point out that it might be misleading to newcomers trying to deploy this stack with the provided instructions.
I'll go ahead and close the issue.
