### ISSUE TITLE
reverse_proxy does is misconfigured

### ISSUE THREAD

**Issue by spara** [dockersamples/atsea-sample-shop-app#99]
error:

2017/07/13 20:07:30 [warn] 1#1: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:1
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:1
2017/07/13 20:07:30 [emerg] 1#1: host not found in upstream "appserver" in /etc/nginx/nginx.conf:46
nginx: [emerg] host not found in upstream "appserver" in /etc/nginx/nginx.conf:46

**Comment by macrivello** [comment]
I believe 'proxy-pass' in https://github.com/dockersamples/atsea-sample-shop-app/blob/master/reverse_proxy/nginx.conf should be http://localhost:8080 to pass along the requests.

**Comment by ManoMarks** [comment]
Is this still relevant?

**Comment by spara** [comment]
no, it is configured correctly

**Comment by vonsago** [comment]
@spara How it's work.I met the same problem
